name: Bot_Cuarto_Espia

on:
  workflow_dispatch:

jobs:
  espionaje:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando codigo
        uses: actions/checkout@v4

      - name: Instalando Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalando librerias y Navegador
        run: |
          pip install playwright  # <--- Esta es la que suele faltar
          playwright install chromium

      - name: Ejecutar Bot Espia
        run: python bot_espia.py

      - name: Guardar Captura
        uses: actions/upload-artifact@v4
        with:
          name: reporte-espia
          path: captura_espia.png
